import { app, BrowserWindow, ipcMain } from 'electron';
import { google } from 'googleapis';
import { authenticate } from '@google-cloud/local-auth';
import path from 'path';
import fs from 'fs';
import { EmailFile } from './types';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true, // Ensure this is true for security
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

app.on('ready', createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// --- GMAIL LOGIC (Moved from main.ts) ---

const SCOPES = ['https://www.googleapis.com/auth/gmail.compose'];
// Note: We use process.cwd() to safely find the file in development
const CREDENTIALS_PATH = path.join(process.cwd(), 'credentials.json'); 

ipcMain.handle('create-drafts', async (_event, files: EmailFile[]) => {
  try {
    let auth = await loadSavedCredentialsIfExist();

    if (!auth) {
      auth = await authenticate({
        scopes: SCOPES,
        keyfilePath: CREDENTIALS_PATH,
      });
      await saveCredentials(auth);
    }

    const gmail = google.gmail({ version: 'v1', auth });

    for (const file of files) {
      await createDraft(gmail, file);
    }

    return `Successfully created ${files.length} drafts!`;
  } catch (error) {
    console.error('GMAIL ERROR:', error);
    throw error;
  }
});


async function createDraft(gmail: any, fileData: EmailFile) {
  // Read file from disk and convert to Base64
  const fileContent = fs.readFileSync(fileData.path).toString('base64');
  
  // Construct MIME message
  const boundary = 'foo_bar_baz';
  const messageParts = [
    `From: me`,
    `To: ${fileData.recipient}`,
    `Cc: ${fileData.cc}`,
    `Subject: ${fileData.subject}`,
    `Content-Type: multipart/mixed; boundary="${boundary}"`,
    ``,
    `--${boundary}`,
    `Content-Type: text/plain; charset="UTF-8"`,
    `MIME-Version: 1.0`,
    `Content-Transfer-Encoding: 7bit`,
    ``,
    `${fileData.body}`,
    ``,
    `--${boundary}`,
    `Content-Type: application/octet-stream; name="${fileData.name}"`,
    `Content-Disposition: attachment; filename="${fileData.name}"`,
    `Content-Transfer-Encoding: base64`,
    ``,
    `${fileContent}`,
    ``,
    `--${boundary}--`,
  ];

  const rawMessage = messageParts.join('\n');
  const encodedMessage = Buffer.from(rawMessage)
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

  await gmail.users.drafts.create({
    userId: 'me',
    requestBody: {
      message: {
        raw: encodedMessage,
      },
    },
  });
}

import { OAuth2Client } from 'google-auth-library';

const TOKEN_PATH = path.join(app.getPath('userData'), 'token.json');

async function loadSavedCredentialsIfExist() {
  try {
    const content = fs.readFileSync(TOKEN_PATH, 'utf-8');
    const credentials = JSON.parse(content);
    return google.auth.fromJSON(credentials) as OAuth2Client;
  } catch {
    return null;
  }
}

async function saveCredentials(client: OAuth2Client) {
  const content = fs.readFileSync(CREDENTIALS_PATH, 'utf-8');
  const keys = JSON.parse(content);
  const key = keys.installed || keys.web;

  const payload = {
    type: 'authorized_user',
    client_id: key.client_id,
    client_secret: key.client_secret,
    refresh_token: client.credentials.refresh_token,
  };

  fs.writeFileSync(TOKEN_PATH, JSON.stringify(payload));
}
